### ISSUE TITLE
Does version 4.11 support bitcode?

### ISSUE THREAD

**Issue by a2hill** [dji-sdk/Mobile-UXSDK-iOS#71]
In the last release iOS Mobile SDK 4.11 now supports bitcode. UXSDK does not mention supporting bitcode in its release notes and when attempting to build a release version of the app I get the error:
> `bitcode bundle could not be generated because '/Users/..../Pods/DJI-UXSDK-iOS/iOS_UXSDK/DJIUXSDK.framework/DJIUXSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/..../Pods/DJI-UXSDK-iOS/iOS_UXSDK/DJIUXSDK.framework/DJIUXSDK' for architecture arm64`

I've enabled bitcode for debug and release variants. Does verison 4.11 of UXSDK-iOS support bitcode?

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/28517'>Zendesk ticket #28517</a>:<br><br>Yes, 4.11 UXSDK does support bitcode

Lisa Fedane
DJI Developer Support

**Comment by a2hill** [comment]
What about the above error? Has DJIUXSDK.framework been tested during an archive (release) build?

Also the Zendesk ticket linked to does not seem to exist?

**Comment by vivekTusiyd** [comment]
Hi @a2hill , i am also getting the same error when trying to archiving. When running on the device it is working fine.

Any help would be much appreciated.

**Comment by vivekTusiyd** [comment]
Hi @a2hill , this issue is fixed with Xcode 11.1. In Xcode 10.0 i was facing the same issue while archiving but app was working fine on device. Again i tried in Xcode 11.1 and everything was fixed .

**Comment by a2hill** [comment]
@vivekTusiyd I’ve tried it with 11.1 now but I am still getting the same error. Is there anything that else that might have changed when you updated to 11.1 (on Mojave)? Are you on Mojave or Catalina?

**Comment by india2sarthak** [comment]
Facing the same issue on Xcode 13.1 with UXSDK 4.14

```
bitcode bundle could not be generated because '{PATH}/Pods/DJI-UXSDK-iOS/iOS_UX_SDK/DJIUXSDK.framework/DJIUXSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '{PATH}/Pods/DJI-UXSDK-iOS/iOS_UX_SDK/DJIUXSDK.framework/DJIUXSDK' for architecture arm64
```

**Comment by mitchrsm** [comment]
any body find a solution to this?
